services:
  web:
    build:
      context: ..
      dockerfile: server/Dev.Dockerfile
    command: '/app/server/scripts/docker/local-run.sh'
    ports:
      - '8080:8080'
      - '9229:9229'
    env_file: .env.local
    volumes:
      - './src:/app/server/src'
